config/routes.rb
Rails.application.routes.draw do
  get '/support_requests/search' => 'support_requests#search'
  put '/support_requests/:id' => 'support_requests#update', as: :update_support_request
  resources :support_requests
  root 'support_requests#index'
end

app/models/support_request.rb
class SupportRequest < ActiveRecord::Base
  paginates_per 7
  validates :name, presence: true
  validates :email, presence: true

  def self.search(term)
    where("name || email || department || message ILIKE ?","%#{term}%")
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/support_requests_controller.rb
class SupportRequestsController < ApplicationController
  before_action :find_support_request, only: [:show, :edit, :update, :destroy]

  def new
    @support_request = SupportRequest.new
  end

  def create
    @support_request = SupportRequest.new support_request_params
    if @support_request.save
      redirect_to support_request_path(@support_request)
      flash[:notice] = "Support Request created successfully!"
    else
      flash[:alert] = "Support Request not created. Please see errors."
      render (:new)
    end
  end

  def index
    @support_requests = SupportRequest.order("status DESC", "updated_at DESC").page params[:page]
  end

  def show
    flip_status if params[:flip]
    redirect_to support_requests_path
  end

  def edit
  end

  def update
    if @support_request.update support_request_params
      redirect_to support_request_path(@support_request)
      flash[:notice] = "Support Request updated successfully!"
    else
      flash[:alert] = "Support Request not updated. See errors."
      render :edit
    end
  end

  def destroy
    @support_request.destroy
    redirect_to support_requests_path
    flash[:alert] = "Support Request deleted successfully."
  end

  def search
    session[:term] = params[:q]
    @results = SupportRequest.search(session[:term]).page params[:page]
  end

  private

  def find_support_request
    @support_request = SupportRequest.find params[:id]
  end

  def support_request_params
    params.require(:support_request).permit(:name, :email, :department, :message, :status)
  end

  def flip_status
    find_support_request
    if @support_request.status == "Not Done"
      @support_request.status = "Done"
      @support_request.save
    else
      @support_request.status = "Not Done"
      @support_request.save
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/support_requests_helper.rb
module SupportRequestsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SupportRequests</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= link_to "All Support Requests", support_requests_path %> |
<%= link_to "New Support Request", new_support_request_path%>
<%= form_tag("/support_requests/search", method: "get") do %>
  <%= text_field_tag(:q, "#{session[:term]}") %>
  <%= submit_tag("Search Support Requests") %>
<% end %>
<%= notice || alert %>
<hr>

<%= yield %>

</body>
</html>

app/views/support_requests/_form.html.erb
<% if @support_request.errors %>
  <ul>
    <% @support_request.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<%= form_for @support_request do |f| %>
  <div>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div>
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>
  <div>
    <%= f.radio_button :department, "sales", :checked => (@support_request.department == "sales") %>
    <%= label_tag(:department_sales, "Sales") %>
    <%= f.radio_button :department, "marketing", :checked => (@support_request.department == "marketing") %>
    <%= label_tag(:department_marketing, "Marketing") %>
    <%= f.radio_button :department, "technical", :checked => (@support_request.department == "technical") %>
    <%= label_tag(:department_technical, "Technical") %>
  </div>
  <div>
    <%= f.label :message %>
    <%= f.text_area :message %>
  </div>
  <%= f.submit %>
<% end %>

app/views/support_requests/edit.html.erb
<h1>Edit Support Request</h1>

<%= render "form" %>

app/views/support_requests/index.html.erb
<h1>All Support Requests</h1>

<% if @support_requests != nil %>
<table width="100%">
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Department</th>
      <th>Message</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @support_requests.each do |support_request| %>
      <tr>
        <td width="10%"><%= support_request.name %></td>
        <td width="15%"><%= mail_to "#{support_request.email}" %></td>
        <td width="10%"><%= support_request.department %></td>
        <td width="50%"><%= support_request.message %></td>
        <td width="15%">
          <%= link_to "View", support_request_path(support_request) %>
          <%= link_to "Edit", edit_support_request_path(support_request) %>
          <%= link_to "Delete", support_request_path(support_request), method: :delete, data: {confirm: "Are you sure you want to delete this support request?"} %>
          <%= link_to support_request.status, support_request_path(support_request, :flip => support_request.id) %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<% else %>
<% end %>

<%= paginate @support_requests %>

app/views/support_requests/new.html.erb
<h1>Create Support Request</h1>

<%= render "form" %>

app/views/support_requests/search.html.erb
<h1>Search Results</h1>
<% if @results.empty? %>
<p>No matches!</p>
<% else %>
<table width="100%">
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Department</th>
      <th>Message</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @results.each do |support_request| %>
      <tr>
        <td width="10%"><%= support_request.name %></td>
        <td width="15%"><%= mail_to "#{support_request.email}" %></td>
        <td width="10%"><%= support_request.department %></td>
        <td width="50%"><%= support_request.message %></td>
        <td width="15%">
          <%= link_to "View", support_request_path(support_request) %>
          <%= link_to "Edit", edit_support_request_path(support_request) %>
          <%= link_to "Delete", support_request_path(support_request), method: :delete, data: {confirm: "Are you sure you want to delete this support request?"} %>
          <%= link_to support_request.status, support_request_path(support_request, :flip => support_request.id) %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<% end %>

<%= paginate @results %>

app/views/support_requests/show.html.erb
<h1>View Support Request</h1>

<p>Name: <%= @support_request.name %><br>
   Email: <%= @support_request.email %><br>
   Department: <%= @support_request.department %><br>
   Status: <%= @support_request.status %></p>
<p>Message: <%= @support_request.message %></p>